name: Run Shell Script

on: [push]

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a shell script
      run: |
        echo "Running shell script"
        # Add your shell commands here
        ls -la
        pwd
